// This file is auto-generated by @hey-api/openapi-ts

export const AuditLogSchema = {
  properties: {
    createdAt: {
      format: 'date-time',
      type: 'string',
    },
    data: {
      type: 'object',
    },
    id: {
      format: 'uuid',
      type: 'string',
    },
    objectId: {
      format: 'uuid',
      type: 'string',
    },
    operationType: {
      minLength: 1,
      type: 'string',
    },
    tableName: {
      minLength: 1,
      type: 'string',
    },
    updatedAt: {
      format: 'date-time',
      type: 'string',
    },
    user: {
      properties: {
        createdAt: {
          format: 'date-time',
          type: 'string',
        },
        email: {
          format: 'email',
          minLength: 1,
          type: 'string',
        },
        id: {
          format: 'uuid',
          type: 'string',
        },
        image: {
          nullable: true,
          type: 'string',
        },
        jobTitle: {
          nullable: true,
          type: 'string',
        },
        mfaEnabled: {
          default: false,
          type: 'boolean',
        },
        mfaVerified: {
          default: false,
          type: 'boolean',
        },
        modifiedById: {
          format: 'uuid',
          type: 'string',
        },
        name: {
          nullable: true,
          type: 'string',
        },
        phone: {
          nullable: true,
          type: 'string',
        },
        primaryOrganizationId: {
          format: 'uuid',
          nullable: true,
          type: 'string',
        },
        updatedAt: {
          format: 'date-time',
          type: 'string',
        },
      },
      type: 'object',
    },
    userId: {
      format: 'uuid',
      type: 'string',
    },
  },
} as const;

export const CreateOrganizationPayloadSchema = {
  properties: {
    domain: {
      minLength: 1,
      type: 'string',
    },
    name: {
      minLength: 1,
      type: 'string',
    },
    ownerId: {
      format: 'uuid',
      type: 'string',
    },
  },
} as const;

export const CreateRolePayloadSchema = {
  properties: {
    description: {
      nullable: true,
      type: 'string',
    },
    name: {
      minLength: 1,
      type: 'string',
    },
    permissions: {
      default: [],
      items: {
        type: 'string',
      },
      type: 'array',
    },
  },
} as const;

export const CreateUserPayloadSchema = {
  properties: {
    email: {
      format: 'email',
      minLength: 1,
      type: 'string',
    },
    jobTitle: {
      nullable: true,
      type: 'string',
    },
    name: {
      nullable: true,
      type: 'string',
    },
    password: {
      minLength: 8,
      type: 'string',
    },
    phone: {
      nullable: true,
      type: 'string',
    },
    roles: {
      items: {
        format: 'uuid',
        type: 'string',
      },
      nullable: true,
      type: 'array',
    },
  },
} as const;

export const ErrorResponseSchema = {
  properties: {
    error: {
      default: 'Bad Request',
      type: 'string',
    },
    message: {
      default:
        'The request could not be understood or was missing required parameters.',
      type: 'string',
    },
  },
} as const;

export const LoginPayloadSchema = {
  properties: {
    Email: {
      format: 'email',
      type: 'string',
    },
    Password: {
      maxLength: 100,
      minLength: 6,
      type: 'string',
    },
  },
} as const;

export const MfaVerifyPayloadSchema = {
  properties: {
    code: {
      maximum: 6,
      minimum: 6,
      type: 'string',
    },
  },
} as const;

export const OrganizationSchema = {
  properties: {
    createdAt: {
      format: 'date-time',
      type: 'string',
    },
    domain: {
      minLength: 1,
      type: 'string',
    },
    id: {
      format: 'uuid',
      type: 'string',
    },
    modifiedBy: {
      properties: {
        createdAt: {
          format: 'date-time',
          type: 'string',
        },
        email: {
          format: 'email',
          minLength: 1,
          type: 'string',
        },
        id: {
          format: 'uuid',
          type: 'string',
        },
        image: {
          nullable: true,
          type: 'string',
        },
        jobTitle: {
          nullable: true,
          type: 'string',
        },
        mfaEnabled: {
          default: false,
          type: 'boolean',
        },
        mfaVerified: {
          default: false,
          type: 'boolean',
        },
        modifiedById: {
          format: 'uuid',
          type: 'string',
        },
        name: {
          nullable: true,
          type: 'string',
        },
        phone: {
          nullable: true,
          type: 'string',
        },
        primaryOrganizationId: {
          format: 'uuid',
          nullable: true,
          type: 'string',
        },
        updatedAt: {
          format: 'date-time',
          type: 'string',
        },
      },
      type: 'object',
    },
    modifiedById: {
      format: 'uuid',
      type: 'string',
    },
    name: {
      minLength: 1,
      type: 'string',
    },
    owner: {
      properties: {
        createdAt: {
          format: 'date-time',
          type: 'string',
        },
        email: {
          format: 'email',
          minLength: 1,
          type: 'string',
        },
        id: {
          format: 'uuid',
          type: 'string',
        },
        image: {
          nullable: true,
          type: 'string',
        },
        jobTitle: {
          nullable: true,
          type: 'string',
        },
        mfaEnabled: {
          default: false,
          type: 'boolean',
        },
        mfaVerified: {
          default: false,
          type: 'boolean',
        },
        modifiedById: {
          format: 'uuid',
          type: 'string',
        },
        name: {
          nullable: true,
          type: 'string',
        },
        phone: {
          nullable: true,
          type: 'string',
        },
        primaryOrganizationId: {
          format: 'uuid',
          nullable: true,
          type: 'string',
        },
        updatedAt: {
          format: 'date-time',
          type: 'string',
        },
      },
      type: 'object',
    },
    ownerId: {
      format: 'uuid',
      type: 'string',
    },
    roles: {
      items: {
        properties: {
          createdAt: {
            format: 'date-time',
            type: 'string',
          },
          description: {
            nullable: true,
            type: 'string',
          },
          id: {
            format: 'uuid',
            type: 'string',
          },
          modifiedById: {
            format: 'uuid',
            type: 'string',
          },
          name: {
            minLength: 1,
            type: 'string',
          },
          permissions: {
            default: [],
            items: {
              type: 'string',
            },
            type: 'array',
          },
          updatedAt: {
            format: 'date-time',
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
    updatedAt: {
      format: 'date-time',
      type: 'string',
    },
    users: {
      items: {
        properties: {
          createdAt: {
            format: 'date-time',
            type: 'string',
          },
          email: {
            format: 'email',
            minLength: 1,
            type: 'string',
          },
          id: {
            format: 'uuid',
            type: 'string',
          },
          image: {
            nullable: true,
            type: 'string',
          },
          jobTitle: {
            nullable: true,
            type: 'string',
          },
          mfaEnabled: {
            default: false,
            type: 'boolean',
          },
          mfaVerified: {
            default: false,
            type: 'boolean',
          },
          modifiedById: {
            format: 'uuid',
            type: 'string',
          },
          name: {
            nullable: true,
            type: 'string',
          },
          phone: {
            nullable: true,
            type: 'string',
          },
          primaryOrganizationId: {
            format: 'uuid',
            nullable: true,
            type: 'string',
          },
          updatedAt: {
            format: 'date-time',
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
  },
} as const;

export const RoleSchema = {
  properties: {
    createdAt: {
      format: 'date-time',
      type: 'string',
    },
    description: {
      nullable: true,
      type: 'string',
    },
    id: {
      format: 'uuid',
      type: 'string',
    },
    modifiedBy: {
      properties: {
        createdAt: {
          format: 'date-time',
          type: 'string',
        },
        email: {
          format: 'email',
          minLength: 1,
          type: 'string',
        },
        id: {
          format: 'uuid',
          type: 'string',
        },
        image: {
          nullable: true,
          type: 'string',
        },
        jobTitle: {
          nullable: true,
          type: 'string',
        },
        mfaEnabled: {
          default: false,
          type: 'boolean',
        },
        mfaVerified: {
          default: false,
          type: 'boolean',
        },
        modifiedById: {
          format: 'uuid',
          type: 'string',
        },
        name: {
          nullable: true,
          type: 'string',
        },
        phone: {
          nullable: true,
          type: 'string',
        },
        primaryOrganizationId: {
          format: 'uuid',
          nullable: true,
          type: 'string',
        },
        updatedAt: {
          format: 'date-time',
          type: 'string',
        },
      },
      type: 'object',
    },
    modifiedById: {
      format: 'uuid',
      type: 'string',
    },
    name: {
      minLength: 1,
      type: 'string',
    },
    organizations: {
      items: {
        properties: {
          createdAt: {
            format: 'date-time',
            type: 'string',
          },
          domain: {
            minLength: 1,
            type: 'string',
          },
          id: {
            format: 'uuid',
            type: 'string',
          },
          modifiedById: {
            format: 'uuid',
            type: 'string',
          },
          name: {
            minLength: 1,
            type: 'string',
          },
          ownerId: {
            format: 'uuid',
            type: 'string',
          },
          updatedAt: {
            format: 'date-time',
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
    permissions: {
      default: [],
      items: {
        type: 'string',
      },
      type: 'array',
    },
    updatedAt: {
      format: 'date-time',
      type: 'string',
    },
    users: {
      items: {
        properties: {
          createdAt: {
            format: 'date-time',
            type: 'string',
          },
          email: {
            format: 'email',
            minLength: 1,
            type: 'string',
          },
          id: {
            format: 'uuid',
            type: 'string',
          },
          image: {
            nullable: true,
            type: 'string',
          },
          jobTitle: {
            nullable: true,
            type: 'string',
          },
          mfaEnabled: {
            default: false,
            type: 'boolean',
          },
          mfaVerified: {
            default: false,
            type: 'boolean',
          },
          modifiedById: {
            format: 'uuid',
            type: 'string',
          },
          name: {
            nullable: true,
            type: 'string',
          },
          phone: {
            nullable: true,
            type: 'string',
          },
          primaryOrganizationId: {
            format: 'uuid',
            nullable: true,
            type: 'string',
          },
          updatedAt: {
            format: 'date-time',
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
  },
} as const;

export const SuccessResponseSchema = {
  properties: {
    item: {
      anyOf: [
        {
          properties: {
            createdAt: {
              format: 'date-time',
              type: 'string',
            },
            email: {
              format: 'email',
              minLength: 1,
              type: 'string',
            },
            id: {
              format: 'uuid',
              type: 'string',
            },
            image: {
              nullable: true,
              type: 'string',
            },
            jobTitle: {
              nullable: true,
              type: 'string',
            },
            mfaEnabled: {
              default: false,
              type: 'boolean',
            },
            mfaVerified: {
              default: false,
              type: 'boolean',
            },
            modifiedBy: {
              properties: {
                createdAt: {
                  format: 'date-time',
                  type: 'string',
                },
                email: {
                  format: 'email',
                  minLength: 1,
                  type: 'string',
                },
                id: {
                  format: 'uuid',
                  type: 'string',
                },
                image: {
                  nullable: true,
                  type: 'string',
                },
                jobTitle: {
                  nullable: true,
                  type: 'string',
                },
                mfaEnabled: {
                  default: false,
                  type: 'boolean',
                },
                mfaVerified: {
                  default: false,
                  type: 'boolean',
                },
                modifiedById: {
                  format: 'uuid',
                  type: 'string',
                },
                name: {
                  nullable: true,
                  type: 'string',
                },
                phone: {
                  nullable: true,
                  type: 'string',
                },
                primaryOrganizationId: {
                  format: 'uuid',
                  nullable: true,
                  type: 'string',
                },
                updatedAt: {
                  format: 'date-time',
                  type: 'string',
                },
              },
              type: 'object',
            },
            modifiedById: {
              format: 'uuid',
              type: 'string',
            },
            name: {
              nullable: true,
              type: 'string',
            },
            organizations: {
              items: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  domain: {
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    minLength: 1,
                    type: 'string',
                  },
                  ownerId: {
                    format: 'uuid',
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
            phone: {
              nullable: true,
              type: 'string',
            },
            primaryOrganizationId: {
              format: 'uuid',
              nullable: true,
              type: 'string',
            },
            roles: {
              items: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  description: {
                    nullable: true,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    minLength: 1,
                    type: 'string',
                  },
                  permissions: {
                    default: [],
                    items: {
                      type: 'string',
                    },
                    type: 'array',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
            updatedAt: {
              format: 'date-time',
              type: 'string',
            },
          },
        },
        {
          properties: {
            createdAt: {
              format: 'date-time',
              type: 'string',
            },
            domain: {
              minLength: 1,
              type: 'string',
            },
            id: {
              format: 'uuid',
              type: 'string',
            },
            modifiedBy: {
              properties: {
                createdAt: {
                  format: 'date-time',
                  type: 'string',
                },
                email: {
                  format: 'email',
                  minLength: 1,
                  type: 'string',
                },
                id: {
                  format: 'uuid',
                  type: 'string',
                },
                image: {
                  nullable: true,
                  type: 'string',
                },
                jobTitle: {
                  nullable: true,
                  type: 'string',
                },
                mfaEnabled: {
                  default: false,
                  type: 'boolean',
                },
                mfaVerified: {
                  default: false,
                  type: 'boolean',
                },
                modifiedById: {
                  format: 'uuid',
                  type: 'string',
                },
                name: {
                  nullable: true,
                  type: 'string',
                },
                phone: {
                  nullable: true,
                  type: 'string',
                },
                primaryOrganizationId: {
                  format: 'uuid',
                  nullable: true,
                  type: 'string',
                },
                updatedAt: {
                  format: 'date-time',
                  type: 'string',
                },
              },
              type: 'object',
            },
            modifiedById: {
              format: 'uuid',
              type: 'string',
            },
            name: {
              minLength: 1,
              type: 'string',
            },
            owner: {
              properties: {
                createdAt: {
                  format: 'date-time',
                  type: 'string',
                },
                email: {
                  format: 'email',
                  minLength: 1,
                  type: 'string',
                },
                id: {
                  format: 'uuid',
                  type: 'string',
                },
                image: {
                  nullable: true,
                  type: 'string',
                },
                jobTitle: {
                  nullable: true,
                  type: 'string',
                },
                mfaEnabled: {
                  default: false,
                  type: 'boolean',
                },
                mfaVerified: {
                  default: false,
                  type: 'boolean',
                },
                modifiedById: {
                  format: 'uuid',
                  type: 'string',
                },
                name: {
                  nullable: true,
                  type: 'string',
                },
                phone: {
                  nullable: true,
                  type: 'string',
                },
                primaryOrganizationId: {
                  format: 'uuid',
                  nullable: true,
                  type: 'string',
                },
                updatedAt: {
                  format: 'date-time',
                  type: 'string',
                },
              },
              type: 'object',
            },
            ownerId: {
              format: 'uuid',
              type: 'string',
            },
            roles: {
              items: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  description: {
                    nullable: true,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    minLength: 1,
                    type: 'string',
                  },
                  permissions: {
                    default: [],
                    items: {
                      type: 'string',
                    },
                    type: 'array',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
            updatedAt: {
              format: 'date-time',
              type: 'string',
            },
            users: {
              items: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
          },
        },
        {
          properties: {
            createdAt: {
              format: 'date-time',
              type: 'string',
            },
            description: {
              nullable: true,
              type: 'string',
            },
            id: {
              format: 'uuid',
              type: 'string',
            },
            modifiedBy: {
              properties: {
                createdAt: {
                  format: 'date-time',
                  type: 'string',
                },
                email: {
                  format: 'email',
                  minLength: 1,
                  type: 'string',
                },
                id: {
                  format: 'uuid',
                  type: 'string',
                },
                image: {
                  nullable: true,
                  type: 'string',
                },
                jobTitle: {
                  nullable: true,
                  type: 'string',
                },
                mfaEnabled: {
                  default: false,
                  type: 'boolean',
                },
                mfaVerified: {
                  default: false,
                  type: 'boolean',
                },
                modifiedById: {
                  format: 'uuid',
                  type: 'string',
                },
                name: {
                  nullable: true,
                  type: 'string',
                },
                phone: {
                  nullable: true,
                  type: 'string',
                },
                primaryOrganizationId: {
                  format: 'uuid',
                  nullable: true,
                  type: 'string',
                },
                updatedAt: {
                  format: 'date-time',
                  type: 'string',
                },
              },
              type: 'object',
            },
            modifiedById: {
              format: 'uuid',
              type: 'string',
            },
            name: {
              minLength: 1,
              type: 'string',
            },
            organizations: {
              items: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  domain: {
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    minLength: 1,
                    type: 'string',
                  },
                  ownerId: {
                    format: 'uuid',
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
            permissions: {
              default: [],
              items: {
                type: 'string',
              },
              type: 'array',
            },
            updatedAt: {
              format: 'date-time',
              type: 'string',
            },
            users: {
              items: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              type: 'array',
            },
          },
        },
        {
          properties: {
            createdAt: {
              format: 'date-time',
              type: 'string',
            },
            data: {
              type: 'object',
            },
            id: {
              format: 'uuid',
              type: 'string',
            },
            objectId: {
              format: 'uuid',
              type: 'string',
            },
            operationType: {
              minLength: 1,
              type: 'string',
            },
            tableName: {
              minLength: 1,
              type: 'string',
            },
            updatedAt: {
              format: 'date-time',
              type: 'string',
            },
            user: {
              properties: {
                createdAt: {
                  format: 'date-time',
                  type: 'string',
                },
                email: {
                  format: 'email',
                  minLength: 1,
                  type: 'string',
                },
                id: {
                  format: 'uuid',
                  type: 'string',
                },
                image: {
                  nullable: true,
                  type: 'string',
                },
                jobTitle: {
                  nullable: true,
                  type: 'string',
                },
                mfaEnabled: {
                  default: false,
                  type: 'boolean',
                },
                mfaVerified: {
                  default: false,
                  type: 'boolean',
                },
                modifiedById: {
                  format: 'uuid',
                  type: 'string',
                },
                name: {
                  nullable: true,
                  type: 'string',
                },
                phone: {
                  nullable: true,
                  type: 'string',
                },
                primaryOrganizationId: {
                  format: 'uuid',
                  nullable: true,
                  type: 'string',
                },
                updatedAt: {
                  format: 'date-time',
                  type: 'string',
                },
              },
              type: 'object',
            },
            userId: {
              format: 'uuid',
              type: 'string',
            },
          },
        },
      ],
    },
    items: {
      items: {
        anyOf: [
          {
            properties: {
              createdAt: {
                format: 'date-time',
                type: 'string',
              },
              email: {
                format: 'email',
                minLength: 1,
                type: 'string',
              },
              id: {
                format: 'uuid',
                type: 'string',
              },
              image: {
                nullable: true,
                type: 'string',
              },
              jobTitle: {
                nullable: true,
                type: 'string',
              },
              mfaEnabled: {
                default: false,
                type: 'boolean',
              },
              mfaVerified: {
                default: false,
                type: 'boolean',
              },
              modifiedBy: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              modifiedById: {
                format: 'uuid',
                type: 'string',
              },
              name: {
                nullable: true,
                type: 'string',
              },
              organizations: {
                items: {
                  properties: {
                    createdAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                    domain: {
                      minLength: 1,
                      type: 'string',
                    },
                    id: {
                      format: 'uuid',
                      type: 'string',
                    },
                    modifiedById: {
                      format: 'uuid',
                      type: 'string',
                    },
                    name: {
                      minLength: 1,
                      type: 'string',
                    },
                    ownerId: {
                      format: 'uuid',
                      type: 'string',
                    },
                    updatedAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                  },
                  type: 'object',
                },
                type: 'array',
              },
              phone: {
                nullable: true,
                type: 'string',
              },
              primaryOrganizationId: {
                format: 'uuid',
                nullable: true,
                type: 'string',
              },
              roles: {
                items: {
                  properties: {
                    createdAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                    description: {
                      nullable: true,
                      type: 'string',
                    },
                    id: {
                      format: 'uuid',
                      type: 'string',
                    },
                    modifiedById: {
                      format: 'uuid',
                      type: 'string',
                    },
                    name: {
                      minLength: 1,
                      type: 'string',
                    },
                    permissions: {
                      default: [],
                      items: {
                        type: 'string',
                      },
                      type: 'array',
                    },
                    updatedAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                  },
                  type: 'object',
                },
                type: 'array',
              },
              updatedAt: {
                format: 'date-time',
                type: 'string',
              },
            },
          },
          {
            properties: {
              createdAt: {
                format: 'date-time',
                type: 'string',
              },
              domain: {
                minLength: 1,
                type: 'string',
              },
              id: {
                format: 'uuid',
                type: 'string',
              },
              modifiedBy: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              modifiedById: {
                format: 'uuid',
                type: 'string',
              },
              name: {
                minLength: 1,
                type: 'string',
              },
              owner: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              ownerId: {
                format: 'uuid',
                type: 'string',
              },
              roles: {
                items: {
                  properties: {
                    createdAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                    description: {
                      nullable: true,
                      type: 'string',
                    },
                    id: {
                      format: 'uuid',
                      type: 'string',
                    },
                    modifiedById: {
                      format: 'uuid',
                      type: 'string',
                    },
                    name: {
                      minLength: 1,
                      type: 'string',
                    },
                    permissions: {
                      default: [],
                      items: {
                        type: 'string',
                      },
                      type: 'array',
                    },
                    updatedAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                  },
                  type: 'object',
                },
                type: 'array',
              },
              updatedAt: {
                format: 'date-time',
                type: 'string',
              },
              users: {
                items: {
                  properties: {
                    createdAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                    email: {
                      format: 'email',
                      minLength: 1,
                      type: 'string',
                    },
                    id: {
                      format: 'uuid',
                      type: 'string',
                    },
                    image: {
                      nullable: true,
                      type: 'string',
                    },
                    jobTitle: {
                      nullable: true,
                      type: 'string',
                    },
                    mfaEnabled: {
                      default: false,
                      type: 'boolean',
                    },
                    mfaVerified: {
                      default: false,
                      type: 'boolean',
                    },
                    modifiedById: {
                      format: 'uuid',
                      type: 'string',
                    },
                    name: {
                      nullable: true,
                      type: 'string',
                    },
                    phone: {
                      nullable: true,
                      type: 'string',
                    },
                    primaryOrganizationId: {
                      format: 'uuid',
                      nullable: true,
                      type: 'string',
                    },
                    updatedAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                  },
                  type: 'object',
                },
                type: 'array',
              },
            },
          },
          {
            properties: {
              createdAt: {
                format: 'date-time',
                type: 'string',
              },
              description: {
                nullable: true,
                type: 'string',
              },
              id: {
                format: 'uuid',
                type: 'string',
              },
              modifiedBy: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              modifiedById: {
                format: 'uuid',
                type: 'string',
              },
              name: {
                minLength: 1,
                type: 'string',
              },
              organizations: {
                items: {
                  properties: {
                    createdAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                    domain: {
                      minLength: 1,
                      type: 'string',
                    },
                    id: {
                      format: 'uuid',
                      type: 'string',
                    },
                    modifiedById: {
                      format: 'uuid',
                      type: 'string',
                    },
                    name: {
                      minLength: 1,
                      type: 'string',
                    },
                    ownerId: {
                      format: 'uuid',
                      type: 'string',
                    },
                    updatedAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                  },
                  type: 'object',
                },
                type: 'array',
              },
              permissions: {
                default: [],
                items: {
                  type: 'string',
                },
                type: 'array',
              },
              updatedAt: {
                format: 'date-time',
                type: 'string',
              },
              users: {
                items: {
                  properties: {
                    createdAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                    email: {
                      format: 'email',
                      minLength: 1,
                      type: 'string',
                    },
                    id: {
                      format: 'uuid',
                      type: 'string',
                    },
                    image: {
                      nullable: true,
                      type: 'string',
                    },
                    jobTitle: {
                      nullable: true,
                      type: 'string',
                    },
                    mfaEnabled: {
                      default: false,
                      type: 'boolean',
                    },
                    mfaVerified: {
                      default: false,
                      type: 'boolean',
                    },
                    modifiedById: {
                      format: 'uuid',
                      type: 'string',
                    },
                    name: {
                      nullable: true,
                      type: 'string',
                    },
                    phone: {
                      nullable: true,
                      type: 'string',
                    },
                    primaryOrganizationId: {
                      format: 'uuid',
                      nullable: true,
                      type: 'string',
                    },
                    updatedAt: {
                      format: 'date-time',
                      type: 'string',
                    },
                  },
                  type: 'object',
                },
                type: 'array',
              },
            },
          },
          {
            properties: {
              createdAt: {
                format: 'date-time',
                type: 'string',
              },
              data: {
                type: 'object',
              },
              id: {
                format: 'uuid',
                type: 'string',
              },
              objectId: {
                format: 'uuid',
                type: 'string',
              },
              operationType: {
                minLength: 1,
                type: 'string',
              },
              tableName: {
                minLength: 1,
                type: 'string',
              },
              updatedAt: {
                format: 'date-time',
                type: 'string',
              },
              user: {
                properties: {
                  createdAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                  email: {
                    format: 'email',
                    minLength: 1,
                    type: 'string',
                  },
                  id: {
                    format: 'uuid',
                    type: 'string',
                  },
                  image: {
                    nullable: true,
                    type: 'string',
                  },
                  jobTitle: {
                    nullable: true,
                    type: 'string',
                  },
                  mfaEnabled: {
                    default: false,
                    type: 'boolean',
                  },
                  mfaVerified: {
                    default: false,
                    type: 'boolean',
                  },
                  modifiedById: {
                    format: 'uuid',
                    type: 'string',
                  },
                  name: {
                    nullable: true,
                    type: 'string',
                  },
                  phone: {
                    nullable: true,
                    type: 'string',
                  },
                  primaryOrganizationId: {
                    format: 'uuid',
                    nullable: true,
                    type: 'string',
                  },
                  updatedAt: {
                    format: 'date-time',
                    type: 'string',
                  },
                },
                type: 'object',
              },
              userId: {
                format: 'uuid',
                type: 'string',
              },
            },
          },
        ],
      },
      type: 'array',
    },
    pageDetails: {
      nullable: true,
      properties: {
        count: {
          minimum: 0,
          type: 'integer',
        },
        currentPage: {
          minimum: 1,
          type: 'integer',
        },
        nextPage: {
          minimum: 2,
          type: 'integer',
        },
        pages: {
          minimum: 0,
          type: 'integer',
        },
        previousPage: {
          minimum: 1,
          type: 'integer',
        },
      },
      type: 'object',
    },
  },
} as const;

export const UpdateOrganizationPayloadSchema = {
  properties: {
    domain: {
      minLength: 1,
      nullable: true,
      type: 'string',
    },
    name: {
      minLength: 1,
      nullable: true,
      type: 'string',
    },
    ownerId: {
      format: 'uuid',
      nullable: true,
      type: 'string',
    },
  },
} as const;

export const UpdateRolePayloadSchema = {
  properties: {
    description: {
      nullable: true,
      type: 'string',
    },
    name: {
      minLength: 1,
      nullable: true,
      type: 'string',
    },
    permissions: {
      default: [],
      items: {
        type: 'string',
      },
      type: 'array',
    },
  },
} as const;

export const UpdateUserPayloadSchema = {
  properties: {
    email: {
      format: 'email',
      minLength: 1,
      nullable: true,
      type: 'string',
    },
    jobTitle: {
      nullable: true,
      type: 'string',
    },
    name: {
      nullable: true,
      type: 'string',
    },
    organizations: {
      items: {
        format: 'uuid',
        type: 'string',
      },
      nullable: true,
      type: 'array',
    },
    phone: {
      nullable: true,
      type: 'string',
    },
    roles: {
      items: {
        format: 'uuid',
        type: 'string',
      },
      nullable: true,
      type: 'array',
    },
  },
} as const;

export const UserSchema = {
  properties: {
    createdAt: {
      format: 'date-time',
      type: 'string',
    },
    email: {
      format: 'email',
      minLength: 1,
      type: 'string',
    },
    id: {
      format: 'uuid',
      type: 'string',
    },
    image: {
      nullable: true,
      type: 'string',
    },
    jobTitle: {
      nullable: true,
      type: 'string',
    },
    mfaEnabled: {
      default: false,
      type: 'boolean',
    },
    mfaVerified: {
      default: false,
      type: 'boolean',
    },
    modifiedBy: {
      properties: {
        createdAt: {
          format: 'date-time',
          type: 'string',
        },
        email: {
          format: 'email',
          minLength: 1,
          type: 'string',
        },
        id: {
          format: 'uuid',
          type: 'string',
        },
        image: {
          nullable: true,
          type: 'string',
        },
        jobTitle: {
          nullable: true,
          type: 'string',
        },
        mfaEnabled: {
          default: false,
          type: 'boolean',
        },
        mfaVerified: {
          default: false,
          type: 'boolean',
        },
        modifiedById: {
          format: 'uuid',
          type: 'string',
        },
        name: {
          nullable: true,
          type: 'string',
        },
        phone: {
          nullable: true,
          type: 'string',
        },
        primaryOrganizationId: {
          format: 'uuid',
          nullable: true,
          type: 'string',
        },
        updatedAt: {
          format: 'date-time',
          type: 'string',
        },
      },
      type: 'object',
    },
    modifiedById: {
      format: 'uuid',
      type: 'string',
    },
    name: {
      nullable: true,
      type: 'string',
    },
    organizations: {
      items: {
        properties: {
          createdAt: {
            format: 'date-time',
            type: 'string',
          },
          domain: {
            minLength: 1,
            type: 'string',
          },
          id: {
            format: 'uuid',
            type: 'string',
          },
          modifiedById: {
            format: 'uuid',
            type: 'string',
          },
          name: {
            minLength: 1,
            type: 'string',
          },
          ownerId: {
            format: 'uuid',
            type: 'string',
          },
          updatedAt: {
            format: 'date-time',
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
    phone: {
      nullable: true,
      type: 'string',
    },
    primaryOrganizationId: {
      format: 'uuid',
      nullable: true,
      type: 'string',
    },
    roles: {
      items: {
        properties: {
          createdAt: {
            format: 'date-time',
            type: 'string',
          },
          description: {
            nullable: true,
            type: 'string',
          },
          id: {
            format: 'uuid',
            type: 'string',
          },
          modifiedById: {
            format: 'uuid',
            type: 'string',
          },
          name: {
            minLength: 1,
            type: 'string',
          },
          permissions: {
            default: [],
            items: {
              type: 'string',
            },
            type: 'array',
          },
          updatedAt: {
            format: 'date-time',
            type: 'string',
          },
        },
        type: 'object',
      },
      type: 'array',
    },
    updatedAt: {
      format: 'date-time',
      type: 'string',
    },
  },
} as const;
