// This file is auto-generated by @hey-api/openapi-ts

export type AuditLog = {
  createdAt?: string;
  data?: {
    [key: string]: unknown;
  };
  id?: string;
  objectId?: string;
  operationType?: string;
  tableName?: string;
  updatedAt?: string;
  user?: {
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  };
  userId?: string;
};

export type ErrorResponse = {
  error?: string;
  message?: string;
};

export type LoginPayload = {
  Email?: string;
  Password?: string;
};

export type MfaVerifyPayload = {
  code?: string;
};

export type Organization = {
  createdAt?: string;
  domain?: string;
  id?: string;
  modifiedBy?: {
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  };
  modifiedById?: string;
  name?: string;
  owner?: {
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  };
  ownerId?: string;
  roles?: Array<{
    createdAt?: string;
    description?: string | null;
    id?: string;
    modifiedById?: string;
    name?: string;
    permissions?: Array<string>;
    updatedAt?: string;
  }>;
  updatedAt?: string;
  users?: Array<{
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  }>;
};

export type Role = {
  createdAt?: string;
  description?: string | null;
  id?: string;
  modifiedBy?: {
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  };
  modifiedById?: string;
  name?: string;
  organizations?: Array<{
    createdAt?: string;
    domain?: string;
    id?: string;
    modifiedById?: string;
    name?: string;
    ownerId?: string;
    updatedAt?: string;
  }>;
  permissions?: Array<string>;
  updatedAt?: string;
  users?: Array<{
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  }>;
};

export type SuccessResponse = {
  item?:
    | {
        createdAt?: string;
        email?: string;
        id?: string;
        image?: string | null;
        jobTitle?: string | null;
        mfaEnabled?: boolean;
        mfaVerified?: boolean;
        modifiedBy?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        modifiedById?: string;
        name?: string | null;
        organizations?: Array<{
          createdAt?: string;
          domain?: string;
          id?: string;
          modifiedById?: string;
          name?: string;
          ownerId?: string;
          updatedAt?: string;
        }>;
        phone?: string | null;
        primaryOrganizationId?: string | null;
        roles?: Array<{
          createdAt?: string;
          description?: string | null;
          id?: string;
          modifiedById?: string;
          name?: string;
          permissions?: Array<string>;
          updatedAt?: string;
        }>;
        updatedAt?: string;
      }
    | {
        createdAt?: string;
        domain?: string;
        id?: string;
        modifiedBy?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        modifiedById?: string;
        name?: string;
        owner?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        ownerId?: string;
        roles?: Array<{
          createdAt?: string;
          description?: string | null;
          id?: string;
          modifiedById?: string;
          name?: string;
          permissions?: Array<string>;
          updatedAt?: string;
        }>;
        updatedAt?: string;
        users?: Array<{
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        }>;
      }
    | {
        createdAt?: string;
        description?: string | null;
        id?: string;
        modifiedBy?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        modifiedById?: string;
        name?: string;
        organizations?: Array<{
          createdAt?: string;
          domain?: string;
          id?: string;
          modifiedById?: string;
          name?: string;
          ownerId?: string;
          updatedAt?: string;
        }>;
        permissions?: Array<string>;
        updatedAt?: string;
        users?: Array<{
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        }>;
      }
    | {
        createdAt?: string;
        data?: {
          [key: string]: unknown;
        };
        id?: string;
        objectId?: string;
        operationType?: string;
        tableName?: string;
        updatedAt?: string;
        user?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        userId?: string;
      };
  items?: Array<
    | {
        createdAt?: string;
        email?: string;
        id?: string;
        image?: string | null;
        jobTitle?: string | null;
        mfaEnabled?: boolean;
        mfaVerified?: boolean;
        modifiedBy?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        modifiedById?: string;
        name?: string | null;
        organizations?: Array<{
          createdAt?: string;
          domain?: string;
          id?: string;
          modifiedById?: string;
          name?: string;
          ownerId?: string;
          updatedAt?: string;
        }>;
        phone?: string | null;
        primaryOrganizationId?: string | null;
        roles?: Array<{
          createdAt?: string;
          description?: string | null;
          id?: string;
          modifiedById?: string;
          name?: string;
          permissions?: Array<string>;
          updatedAt?: string;
        }>;
        updatedAt?: string;
      }
    | {
        createdAt?: string;
        domain?: string;
        id?: string;
        modifiedBy?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        modifiedById?: string;
        name?: string;
        owner?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        ownerId?: string;
        roles?: Array<{
          createdAt?: string;
          description?: string | null;
          id?: string;
          modifiedById?: string;
          name?: string;
          permissions?: Array<string>;
          updatedAt?: string;
        }>;
        updatedAt?: string;
        users?: Array<{
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        }>;
      }
    | {
        createdAt?: string;
        description?: string | null;
        id?: string;
        modifiedBy?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        modifiedById?: string;
        name?: string;
        organizations?: Array<{
          createdAt?: string;
          domain?: string;
          id?: string;
          modifiedById?: string;
          name?: string;
          ownerId?: string;
          updatedAt?: string;
        }>;
        permissions?: Array<string>;
        updatedAt?: string;
        users?: Array<{
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        }>;
      }
    | {
        createdAt?: string;
        data?: {
          [key: string]: unknown;
        };
        id?: string;
        objectId?: string;
        operationType?: string;
        tableName?: string;
        updatedAt?: string;
        user?: {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedById?: string;
          name?: string | null;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          updatedAt?: string;
        };
        userId?: string;
      }
  >;
  pageDetails?: {
    count?: number;
    currentPage?: number;
    nextPage?: number;
    pages?: number;
    previousPage?: number;
  } | null;
};

export type User = {
  createdAt?: string;
  email?: string;
  id?: string;
  image?: string | null;
  jobTitle?: string | null;
  mfaEnabled?: boolean;
  mfaVerified?: boolean;
  modifiedBy?: {
    createdAt?: string;
    email?: string;
    id?: string;
    image?: string | null;
    jobTitle?: string | null;
    mfaEnabled?: boolean;
    mfaVerified?: boolean;
    modifiedById?: string;
    name?: string | null;
    phone?: string | null;
    primaryOrganizationId?: string | null;
    updatedAt?: string;
  };
  modifiedById?: string;
  name?: string | null;
  organizations?: Array<{
    createdAt?: string;
    domain?: string;
    id?: string;
    modifiedById?: string;
    name?: string;
    ownerId?: string;
    updatedAt?: string;
  }>;
  phone?: string | null;
  primaryOrganizationId?: string | null;
  roles?: Array<{
    createdAt?: string;
    description?: string | null;
    id?: string;
    modifiedById?: string;
    name?: string;
    permissions?: Array<string>;
    updatedAt?: string;
  }>;
  updatedAt?: string;
};

export type GetApiAuthenticationCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/check';
};

export type GetApiAuthenticationCheckErrors = {
  /**
   * Unauthorized
   */
  401: {
    error?: string;
    message?: string;
  };
  /**
   * Internal server error.
   */
  500: {
    error?: string;
    message?: string;
  };
  default: unknown;
};

export type GetApiAuthenticationCheckError =
  GetApiAuthenticationCheckErrors[keyof GetApiAuthenticationCheckErrors];

export type GetApiAuthenticationCheckResponses = {
  /**
   * Successful authentication check.
   */
  200: {
    item?:
      | {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedBy?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          modifiedById?: string;
          name?: string | null;
          organizations?: Array<{
            createdAt?: string;
            domain?: string;
            id?: string;
            modifiedById?: string;
            name?: string;
            ownerId?: string;
            updatedAt?: string;
          }>;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          roles?: Array<{
            createdAt?: string;
            description?: string | null;
            id?: string;
            modifiedById?: string;
            name?: string;
            permissions?: Array<string>;
            updatedAt?: string;
          }>;
          updatedAt?: string;
        }
      | {
          createdAt?: string;
          domain?: string;
          id?: string;
          modifiedBy?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          modifiedById?: string;
          name?: string;
          owner?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          ownerId?: string;
          roles?: Array<{
            createdAt?: string;
            description?: string | null;
            id?: string;
            modifiedById?: string;
            name?: string;
            permissions?: Array<string>;
            updatedAt?: string;
          }>;
          updatedAt?: string;
          users?: Array<{
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          }>;
        }
      | {
          createdAt?: string;
          description?: string | null;
          id?: string;
          modifiedBy?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          modifiedById?: string;
          name?: string;
          organizations?: Array<{
            createdAt?: string;
            domain?: string;
            id?: string;
            modifiedById?: string;
            name?: string;
            ownerId?: string;
            updatedAt?: string;
          }>;
          permissions?: Array<string>;
          updatedAt?: string;
          users?: Array<{
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          }>;
        }
      | {
          createdAt?: string;
          data?: {
            [key: string]: unknown;
          };
          id?: string;
          objectId?: string;
          operationType?: string;
          tableName?: string;
          updatedAt?: string;
          user?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          userId?: string;
        };
    items?: Array<
      | {
          createdAt?: string;
          email?: string;
          id?: string;
          image?: string | null;
          jobTitle?: string | null;
          mfaEnabled?: boolean;
          mfaVerified?: boolean;
          modifiedBy?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          modifiedById?: string;
          name?: string | null;
          organizations?: Array<{
            createdAt?: string;
            domain?: string;
            id?: string;
            modifiedById?: string;
            name?: string;
            ownerId?: string;
            updatedAt?: string;
          }>;
          phone?: string | null;
          primaryOrganizationId?: string | null;
          roles?: Array<{
            createdAt?: string;
            description?: string | null;
            id?: string;
            modifiedById?: string;
            name?: string;
            permissions?: Array<string>;
            updatedAt?: string;
          }>;
          updatedAt?: string;
        }
      | {
          createdAt?: string;
          domain?: string;
          id?: string;
          modifiedBy?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          modifiedById?: string;
          name?: string;
          owner?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          ownerId?: string;
          roles?: Array<{
            createdAt?: string;
            description?: string | null;
            id?: string;
            modifiedById?: string;
            name?: string;
            permissions?: Array<string>;
            updatedAt?: string;
          }>;
          updatedAt?: string;
          users?: Array<{
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          }>;
        }
      | {
          createdAt?: string;
          description?: string | null;
          id?: string;
          modifiedBy?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          modifiedById?: string;
          name?: string;
          organizations?: Array<{
            createdAt?: string;
            domain?: string;
            id?: string;
            modifiedById?: string;
            name?: string;
            ownerId?: string;
            updatedAt?: string;
          }>;
          permissions?: Array<string>;
          updatedAt?: string;
          users?: Array<{
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          }>;
        }
      | {
          createdAt?: string;
          data?: {
            [key: string]: unknown;
          };
          id?: string;
          objectId?: string;
          operationType?: string;
          tableName?: string;
          updatedAt?: string;
          user?: {
            createdAt?: string;
            email?: string;
            id?: string;
            image?: string | null;
            jobTitle?: string | null;
            mfaEnabled?: boolean;
            mfaVerified?: boolean;
            modifiedById?: string;
            name?: string | null;
            phone?: string | null;
            primaryOrganizationId?: string | null;
            updatedAt?: string;
          };
          userId?: string;
        }
    >;
    pageDetails?: {
      count?: number;
      currentPage?: number;
      nextPage?: number;
      pages?: number;
      previousPage?: number;
    } | null;
  };
};

export type GetApiAuthenticationCheckResponse =
  GetApiAuthenticationCheckResponses[keyof GetApiAuthenticationCheckResponses];

export type PostApiAuthenticationLoginData = {
  body: {
    Email?: string;
    Password?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/login';
};

export type PostApiAuthenticationLoginErrors = {
  /**
   * Invalid request.
   */
  400: {
    error?: string;
    message?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    error?: string;
    message?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    error?: string;
    message?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationLoginError =
  PostApiAuthenticationLoginErrors[keyof PostApiAuthenticationLoginErrors];

export type PostApiAuthenticationLoginResponses = {
  /**
   * The user has been successfully logged in.
   */
  200: unknown;
};

export type PostApiAuthenticationLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/logout';
};

export type PostApiAuthenticationLogoutErrors = {
  /**
   * Unauthorized
   */
  401: {
    error?: string;
    message?: string;
  };
  /**
   * Internal server error.
   */
  500: {
    error?: string;
    message?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationLogoutError =
  PostApiAuthenticationLogoutErrors[keyof PostApiAuthenticationLogoutErrors];

export type PostApiAuthenticationLogoutResponses = {
  /**
   * Successful logout.
   */
  200: unknown;
};

export type GetApiAuthenticationMfaEnableData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/enable';
};

export type GetApiAuthenticationMfaEnableErrors = {
  /**
   * Unauthorized
   */
  401: {
    error?: string;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    error?: string;
    message?: string;
  };
  default: unknown;
};

export type GetApiAuthenticationMfaEnableError =
  GetApiAuthenticationMfaEnableErrors[keyof GetApiAuthenticationMfaEnableErrors];

export type GetApiAuthenticationMfaEnableResponses = {
  /**
   * The MFA QR code has been successfully generated and returned.
   */
  200: unknown;
};

export type PostApiAuthenticationMfaVerifyData = {
  body: {
    code?: string;
  };
  path?: never;
  query?: never;
  url: '/api/authentication/mfa/verify';
};

export type PostApiAuthenticationMfaVerifyErrors = {
  /**
   * Bad Request
   */
  400: {
    error?: string;
    message?: string;
  };
  /**
   * Unauthorized
   */
  401: {
    error?: string;
    message?: string;
  };
  /**
   * Internal server error
   */
  500: {
    error?: string;
    message?: string;
  };
  default: unknown;
};

export type PostApiAuthenticationMfaVerifyError =
  PostApiAuthenticationMfaVerifyErrors[keyof PostApiAuthenticationMfaVerifyErrors];

export type PostApiAuthenticationMfaVerifyResponses = {
  /**
   * MFA verification successful.
   */
  200: unknown;
};

export type PostApiUsersData = {
  body: {
    email?: string;
    jobTitle?: string | null;
    name?: string | null;
    password?: string;
    phone?: string | null;
    roles?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/api/users';
};

export type PostApiUsersErrors = {
  /**
   * Invalid request.
   */
  400: {
    error?: string;
    message?: string;
  };
  /**
   * Unauthorized.
   */
  401: {
    error?: string;
    message?: string;
  };
  /**
   * Internal Server Error.
   */
  500: {
    error?: string;
    message?: string;
  };
  default: unknown;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
  /**
   * The user has been successfully created.
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: 'http://localhost:6173' | 'https://one.thusa.co.za' | (string & {});
};
