/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as AuditLogsIndexRouteImport } from './routes/audit-logs/index'
import { Route as UsersCreateRouteImport } from './routes/users/create'
import { Route as RolesCreateRouteImport } from './routes/roles/create'
import { Route as MaterialsCreateRouteImport } from './routes/materials/create'
import { Route as AuditLogsIdRouteImport } from './routes/audit-logs/$id'
import { Route as UsersIdIndexRouteImport } from './routes/users/$id/index'
import { Route as RolesIdIndexRouteImport } from './routes/roles/$id/index'
import { Route as MaterialsIdIndexRouteImport } from './routes/materials/$id/index'
import { Route as UsersIdEditRouteImport } from './routes/users/$id/edit'
import { Route as RolesIdPermissionsRouteImport } from './routes/roles/$id/permissions'
import { Route as RolesIdEditRouteImport } from './routes/roles/$id/edit'
import { Route as MaterialsIdEditRouteImport } from './routes/materials/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIndexRoute = AuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesCreateRoute = RolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsCreateRoute = MaterialsCreateRouteImport.update({
  id: '/materials/create',
  path: '/materials/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIdRoute = AuditLogsIdRouteImport.update({
  id: '/audit-logs/$id',
  path: '/audit-logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdIndexRoute = UsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdIndexRoute = RolesIdIndexRouteImport.update({
  id: '/roles/$id/',
  path: '/roles/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIdIndexRoute = MaterialsIdIndexRouteImport.update({
  id: '/materials/$id/',
  path: '/materials/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdPermissionsRoute = RolesIdPermissionsRouteImport.update({
  id: '/roles/$id/permissions',
  path: '/roles/$id/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdEditRoute = RolesIdEditRouteImport.update({
  id: '/roles/$id/edit',
  path: '/roles/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIdEditRoute = MaterialsIdEditRouteImport.update({
  id: '/materials/$id/edit',
  path: '/materials/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/materials/create': typeof MaterialsCreateRoute
  '/roles/create': typeof RolesCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/materials/$id/edit': typeof MaterialsIdEditRoute
  '/roles/$id/edit': typeof RolesIdEditRoute
  '/roles/$id/permissions': typeof RolesIdPermissionsRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/materials/$id': typeof MaterialsIdIndexRoute
  '/roles/$id': typeof RolesIdIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/materials/create': typeof MaterialsCreateRoute
  '/roles/create': typeof RolesCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/materials/$id/edit': typeof MaterialsIdEditRoute
  '/roles/$id/edit': typeof RolesIdEditRoute
  '/roles/$id/permissions': typeof RolesIdPermissionsRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/materials/$id': typeof MaterialsIdIndexRoute
  '/roles/$id': typeof RolesIdIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/materials/create': typeof MaterialsCreateRoute
  '/roles/create': typeof RolesCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/materials/$id/edit': typeof MaterialsIdEditRoute
  '/roles/$id/edit': typeof RolesIdEditRoute
  '/roles/$id/permissions': typeof RolesIdPermissionsRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/materials/$id/': typeof MaterialsIdIndexRoute
  '/roles/$id/': typeof RolesIdIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs/$id'
    | '/materials/create'
    | '/roles/create'
    | '/users/create'
    | '/audit-logs'
    | '/materials'
    | '/roles'
    | '/users'
    | '/materials/$id/edit'
    | '/roles/$id/edit'
    | '/roles/$id/permissions'
    | '/users/$id/edit'
    | '/materials/$id'
    | '/roles/$id'
    | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs/$id'
    | '/materials/create'
    | '/roles/create'
    | '/users/create'
    | '/audit-logs'
    | '/materials'
    | '/roles'
    | '/users'
    | '/materials/$id/edit'
    | '/roles/$id/edit'
    | '/roles/$id/permissions'
    | '/users/$id/edit'
    | '/materials/$id'
    | '/roles/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/'
    | '/audit-logs/$id'
    | '/materials/create'
    | '/roles/create'
    | '/users/create'
    | '/audit-logs/'
    | '/materials/'
    | '/roles/'
    | '/users/'
    | '/materials/$id/edit'
    | '/roles/$id/edit'
    | '/roles/$id/permissions'
    | '/users/$id/edit'
    | '/materials/$id/'
    | '/roles/$id/'
    | '/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsIdRoute: typeof AuditLogsIdRoute
  MaterialsCreateRoute: typeof MaterialsCreateRoute
  RolesCreateRoute: typeof RolesCreateRoute
  UsersCreateRoute: typeof UsersCreateRoute
  AuditLogsIndexRoute: typeof AuditLogsIndexRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  MaterialsIdEditRoute: typeof MaterialsIdEditRoute
  RolesIdEditRoute: typeof RolesIdEditRoute
  RolesIdPermissionsRoute: typeof RolesIdPermissionsRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
  MaterialsIdIndexRoute: typeof MaterialsIdIndexRoute
  RolesIdIndexRoute: typeof RolesIdIndexRoute
  UsersIdIndexRoute: typeof UsersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/': {
      id: '/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/create': {
      id: '/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof RolesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/create': {
      id: '/materials/create'
      path: '/materials/create'
      fullPath: '/materials/create'
      preLoaderRoute: typeof MaterialsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/$id': {
      id: '/audit-logs/$id'
      path: '/audit-logs/$id'
      fullPath: '/audit-logs/$id'
      preLoaderRoute: typeof AuditLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/': {
      id: '/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$id/': {
      id: '/roles/$id/'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof RolesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$id/': {
      id: '/materials/$id/'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof MaterialsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$id/permissions': {
      id: '/roles/$id/permissions'
      path: '/roles/$id/permissions'
      fullPath: '/roles/$id/permissions'
      preLoaderRoute: typeof RolesIdPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$id/edit': {
      id: '/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/roles/$id/edit'
      preLoaderRoute: typeof RolesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$id/edit': {
      id: '/materials/$id/edit'
      path: '/materials/$id/edit'
      fullPath: '/materials/$id/edit'
      preLoaderRoute: typeof MaterialsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsIdRoute: AuditLogsIdRoute,
  MaterialsCreateRoute: MaterialsCreateRoute,
  RolesCreateRoute: RolesCreateRoute,
  UsersCreateRoute: UsersCreateRoute,
  AuditLogsIndexRoute: AuditLogsIndexRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  MaterialsIdEditRoute: MaterialsIdEditRoute,
  RolesIdEditRoute: RolesIdEditRoute,
  RolesIdPermissionsRoute: RolesIdPermissionsRoute,
  UsersIdEditRoute: UsersIdEditRoute,
  MaterialsIdIndexRoute: MaterialsIdIndexRoute,
  RolesIdIndexRoute: RolesIdIndexRoute,
  UsersIdIndexRoute: UsersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
